//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TalentoDigital.wsProyectoFinal {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProyectoFinalSoap", Namespace="http://tempuri.org/")]
    public partial class ProyectoFinal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProductoIndexOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProyectoFinal() {
            this.Url = global::TalentoDigital.Properties.Settings.Default.TalentoDigital_wsProyectoFinal_ProyectoFinal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProductoIndexCompletedEventHandler ProductoIndexCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProductoIndex", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductoIndexDTO[] ProductoIndex() {
            object[] results = this.Invoke("ProductoIndex", new object[0]);
            return ((ProductoIndexDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void ProductoIndexAsync() {
            this.ProductoIndexAsync(null);
        }
        
        /// <remarks/>
        public void ProductoIndexAsync(object userState) {
            if ((this.ProductoIndexOperationCompleted == null)) {
                this.ProductoIndexOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductoIndexOperationCompleted);
            }
            this.InvokeAsync("ProductoIndex", new object[0], this.ProductoIndexOperationCompleted, userState);
        }
        
        private void OnProductoIndexOperationCompleted(object arg) {
            if ((this.ProductoIndexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductoIndexCompleted(this, new ProductoIndexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoIndexDTO {
        
        private string iD_PRODUCTOField;
        
        private string cOD_PRODUCTOField;
        
        private string dESCRIPCION_PRODUCTOField;
        
        private decimal eXISTENCIAField;
        
        private string dESCRIPCION_CLASE_PRODUCTOField;
        
        private string dESCRIPCION_UNIDAD_MEDIDAField;
        
        /// <remarks/>
        public string ID_PRODUCTO {
            get {
                return this.iD_PRODUCTOField;
            }
            set {
                this.iD_PRODUCTOField = value;
            }
        }
        
        /// <remarks/>
        public string COD_PRODUCTO {
            get {
                return this.cOD_PRODUCTOField;
            }
            set {
                this.cOD_PRODUCTOField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRIPCION_PRODUCTO {
            get {
                return this.dESCRIPCION_PRODUCTOField;
            }
            set {
                this.dESCRIPCION_PRODUCTOField = value;
            }
        }
        
        /// <remarks/>
        public decimal EXISTENCIA {
            get {
                return this.eXISTENCIAField;
            }
            set {
                this.eXISTENCIAField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRIPCION_CLASE_PRODUCTO {
            get {
                return this.dESCRIPCION_CLASE_PRODUCTOField;
            }
            set {
                this.dESCRIPCION_CLASE_PRODUCTOField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRIPCION_UNIDAD_MEDIDA {
            get {
                return this.dESCRIPCION_UNIDAD_MEDIDAField;
            }
            set {
                this.dESCRIPCION_UNIDAD_MEDIDAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ProductoIndexCompletedEventHandler(object sender, ProductoIndexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductoIndexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductoIndexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductoIndexDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductoIndexDTO[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591