//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int CodInventario { get; set; }
        public int CodBodega { get; set; }
        public int CodProducto { get; set; }
        public int Existencia { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public decimal Precio { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
